param(
    [Parameter(Mandatory = $true)][string]$OutFile
)
$ErrorActionPreference = "Stop"
$outFile = $OutFile

$proc = Get-CimInstance Win32_Processor | Select-Object -First 1
$name = $proc.Name.Trim()
$cores = [int]$proc.NumberOfCores
$logical = [int]$proc.NumberOfLogicalProcessors
if ($cores -lt 1) { $cores = $logical }
$hostThreads = $cores
if ($hostThreads -lt 1) { $hostThreads = 4 }

$archFlag = ""
$isa = "baseline"

$isaCode = @"
using System;
using System.Runtime.InteropServices;
public static class GemmaCpuIsa {
    [DllImport("kernel32.dll")]
    static extern bool IsProcessorFeaturePresent(uint feature);
    public static string Detect() {
        if (IsProcessorFeaturePresent(41)) return "AVX512";
        if (IsProcessorFeaturePresent(40)) return "AVX2";
        if (IsProcessorFeaturePresent(39)) return "AVX";
        return "baseline";
    }
}
"@
Add-Type -TypeDefinition $isaCode -Language CSharp
$isa = [GemmaCpuIsa]::Detect()

switch ($isa) {
    "AVX512" { $archFlag = "/arch:AVX512" }
    "AVX2"   { $archFlag = "/arch:AVX2" }
    "AVX"    { $archFlag = "/arch:AVX" }
    default  { $archFlag = "" }
}

$cmake = @"
# Auto-generated by scripts/detect_cpu.ps1 — do not edit
set(GEMMA_CPU_NAME "$($name -replace '"','\"')" CACHE STRING "Host CPU model" FORCE)
set(GEMMA_HOST_THREADS $hostThreads CACHE STRING "Physical cores for host-side pools" FORCE)
set(GEMMA_HOST_LOGICAL $logical CACHE STRING "Logical processors" FORCE)
set(GEMMA_HOST_ISA "$isa" CACHE STRING "Detected ISA tier" FORCE)
set(GEMMA_MSVC_ARCH_FLAG "$archFlag" CACHE STRING "MSVC /arch flag for host code" FORCE)
set(GEMMA_HOST_OPENMP ON CACHE BOOL "OpenMP for host parallel in linked libs" FORCE)
"@

New-Item -ItemType Directory -Force -Path (Split-Path $outFile) | Out-Null
Set-Content -Path $outFile -Value $cmake -Encoding utf8

Write-Host "CPU: $name"
Write-Host "cores=$cores logical=$logical host_threads=$hostThreads isa=$isa msvc_arch=$archFlag"
Write-Host "wrote $outFile"
