# Auto-generated by scripts/detect_cpu.ps1 â€” do not edit
set(GEMMA_CPU_NAME "Intel(R) Core(TM) i7-4790S CPU @ 3.20GHz" CACHE STRING "Host CPU model" FORCE)
set(GEMMA_HOST_THREADS 4 CACHE STRING "Physical cores for host-side pools" FORCE)
set(GEMMA_HOST_LOGICAL 8 CACHE STRING "Logical processors" FORCE)
set(GEMMA_HOST_ISA "AVX2" CACHE STRING "Detected ISA tier" FORCE)
set(GEMMA_MSVC_ARCH_FLAG "/arch:AVX2" CACHE STRING "MSVC /arch flag for host code" FORCE)
set(GEMMA_HOST_OPENMP ON CACHE BOOL "OpenMP for host parallel in linked libs" FORCE)
